//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManBox.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckoutMetadata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckoutMetadata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManBox.Common.Resources.CheckoutMetadata", typeof(CheckoutMetadata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans quelle ville?.
        /// </summary>
        public static string ErrorCityRequired {
            get {
                return ResourceManager.GetString("ErrorCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse mail invalide.
        /// </summary>
        public static string ErrorEmailFormat {
            get {
                return ResourceManager.GetString("ErrorEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail obligatoire.
        /// </summary>
        public static string ErrorEmailRequired {
            get {
                return ResourceManager.GetString("ErrorEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ouch pas de prénom!.
        /// </summary>
        public static string ErrorFirstNameRequired {
            get {
                return ResourceManager.GetString("ErrorFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom trop long (twss).
        /// </summary>
        public static string ErrorFirstNameTooLong {
            get {
                return ResourceManager.GetString("ErrorFirstNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sans nom ça va être dur.
        /// </summary>
        public static string ErrorLastNameRequired {
            get {
                return ResourceManager.GetString("ErrorLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom trop long.
        /// </summary>
        public static string ErrorLastNameTooLong {
            get {
                return ResourceManager.GetString("ErrorLastNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format de mot de passe invalide.
        /// </summary>
        public static string ErrorPasswordFormat {
            get {
                return ResourceManager.GetString("ErrorPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe manquant (ou loggez-vous avec Facebook).
        /// </summary>
        public static string ErrorPasswordRequired {
            get {
                return ResourceManager.GetString("ErrorPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone trop long.
        /// </summary>
        public static string ErrorPhoneTooLong {
            get {
                return ResourceManager.GetString("ErrorPhoneTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone trop court.
        /// </summary>
        public static string ErrorPhoneTooShort {
            get {
                return ResourceManager.GetString("ErrorPhoneTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avec quel code postal?.
        /// </summary>
        public static string ErrorPostalCodeRequired {
            get {
                return ResourceManager.GetString("ErrorPostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans quel département?.
        /// </summary>
        public static string ErrorProvinceRequired {
            get {
                return ResourceManager.GetString("ErrorProvinceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to va falloir une adresse pour envoyer ça.
        /// </summary>
        public static string ErrorStreetRequired {
            get {
                return ResourceManager.GetString("ErrorStreetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postal.
        /// </summary>
        public static string LabelPostalCode {
            get {
                return ResourceManager.GetString("LabelPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Département.
        /// </summary>
        public static string LabelProvince {
            get {
                return ResourceManager.GetString("LabelProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse postale.
        /// </summary>
        public static string LabelStreet {
            get {
                return ResourceManager.GetString("LabelStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rue 2.
        /// </summary>
        public static string LabelStreet2 {
            get {
                return ResourceManager.GetString("LabelStreet2", resourceCulture);
            }
        }
    }
}
