//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManBox.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UITexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UITexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManBox.Common.Resources.UITexts", typeof(UITexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre adresse a été mise à jour.
        /// </summary>
        public static string AccountAddressChangeOK {
            get {
                return ResourceManager.GetString("AccountAddressChangeOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon adresse de livraison.
        /// </summary>
        public static string AccountAddressUpdate {
            get {
                return ResourceManager.GetString("AccountAddressUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes commandes.
        /// </summary>
        public static string AccountMyOrders {
            get {
                return ResourceManager.GetString("AccountMyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changement de mot de passe.
        /// </summary>
        public static string AccountPasswordChange {
            get {
                return ResourceManager.GetString("AccountPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre mot de passe a été mis à jour.
        /// </summary>
        public static string AccountPasswordChangeOK {
            get {
                return ResourceManager.GetString("AccountPasswordChangeOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je veux avancer cette livraison et la recevoir le plus tôt possible.
        /// </summary>
        public static string AccountRushLbl {
            get {
                return ResourceManager.GetString("AccountRushLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je veux reporter cette livraison de.
        /// </summary>
        public static string AccountSnoozeOfLbl {
            get {
                return ResourceManager.GetString("AccountSnoozeOfLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semaine(s).
        /// </summary>
        public static string AccountSnoozeWeeks {
            get {
                return ResourceManager.GetString("AccountSnoozeWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les produits.
        /// </summary>
        public static string AllProducts {
            get {
                return ResourceManager.GetString("AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déjà inscrit?.
        /// </summary>
        public static string AlreadyMember {
            get {
                return ResourceManager.GetString("AlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version archivée de ManBox. Ce service n&apos;est plus disponible actuellement..
        /// </summary>
        public static string ArchivedVersion {
            get {
                return ResourceManager.GetString("ArchivedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;authentifier.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string BackBtn {
            get {
                return ResourceManager.GetString("BackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string BlogPostsTitle {
            get {
                return ResourceManager.GetString("BlogPostsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler les modifications.
        /// </summary>
        public static string CartCancelModifBtn {
            get {
                return ResourceManager.GetString("CartCancelModifBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander .
        /// </summary>
        public static string CartCheckoutBtn {
            get {
                return ResourceManager.GetString("CartCheckoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez déjà les produits que vous voulez. Dans trois mois nous verrons avec vous ce que vous voulez modifier dans votre sélection..
        /// </summary>
        public static string CartEmptyNotif {
            get {
                return ResourceManager.GetString("CartEmptyNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas modifier votre sélection pour le moment car votre livraison est en préparation..
        /// </summary>
        public static string CartFrozenNotif {
            get {
                return ResourceManager.GetString("CartFrozenNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraison: &lt;strong&gt;tous les 3 mois&lt;/strong&gt;.
        /// </summary>
        public static string CartInfo {
            get {
                return ResourceManager.GetString("CartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir ma sélection.
        /// </summary>
        public static string CartMobileSelectionBtn {
            get {
                return ResourceManager.GetString("CartMobileSelectionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si vous le souhaitez, vous pouvez changer le contenu de votre abonnement dont la prochaine livraison aura lieu le .
        /// </summary>
        public static string CartModificationNotif {
            get {
                return ResourceManager.GetString("CartModificationNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier ma ManBox.
        /// </summary>
        public static string CartModifyBtn {
            get {
                return ResourceManager.GetString("CartModifyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraison.
        /// </summary>
        public static string CartShippingFee {
            get {
                return ResourceManager.GetString("CartShippingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-total.
        /// </summary>
        public static string CartSubTotal {
            get {
                return ResourceManager.GetString("CartSubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string CartTotal {
            get {
                return ResourceManager.GetString("CartTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  J&apos;accepte les &lt;a href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;Conditions générales&lt;/a&gt; de ManBox. ManBox s’engage à ne divulguer en aucun cas vos informations personnelles à des tiers..
        /// </summary>
        public static string CheckoutAcceptConditions {
            get {
                return ResourceManager.GetString("CheckoutAcceptConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes déjà inscrit. Authentifiez-vous afin de modifier votre abonnement..
        /// </summary>
        public static string CheckoutAlreadyMemberMessage {
            get {
                return ResourceManager.GetString("CheckoutAlreadyMemberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de la carte.
        /// </summary>
        public static string CheckoutCCCardNumber {
            get {
                return ResourceManager.GetString("CheckoutCCCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;expiration (mm/aaaa).
        /// </summary>
        public static string CheckoutCCExpiryDate {
            get {
                return ResourceManager.GetString("CheckoutCCExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulaire de la carte.
        /// </summary>
        public static string CheckoutCCHolderName {
            get {
                return ResourceManager.GetString("CheckoutCCHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer avec.
        /// </summary>
        public static string CheckoutCCPayWith {
            get {
                return ResourceManager.GetString("CheckoutCCPayWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de vérification.
        /// </summary>
        public static string CheckoutCCVerificationCode {
            get {
                return ResourceManager.GetString("CheckoutCCVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fréquence.
        /// </summary>
        public static string CheckoutFrequence {
            get {
                return ResourceManager.GetString("CheckoutFrequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les 3 mois.
        /// </summary>
        public static string CheckoutFrequenceValue {
            get {
                return ResourceManager.GetString("CheckoutFrequenceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez vérifier votre taille avant de continuer..
        /// </summary>
        public static string CheckoutSizeTitle {
            get {
                return ResourceManager.GetString("CheckoutSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez vérifier votre taille.
        /// </summary>
        public static string CheckoutSizeVerify {
            get {
                return ResourceManager.GetString("CheckoutSizeVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a un problème avec les données que vous avez entré..
        /// </summary>
        public static string CheckoutValidationFailedMessage {
            get {
                return ResourceManager.GetString("CheckoutValidationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir vos commandes.
        /// </summary>
        public static string CheckYourOrders {
            get {
                return ResourceManager.GetString("CheckYourOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string CloseBtn {
            get {
                return ResourceManager.GetString("CloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;ManBox a cessé ses activités&lt;h3&gt;&lt;h4&gt;On a essayé.&lt;/h4&gt; &lt;h4&gt;Encore merci.&lt;/h4&gt; &lt;a class=&quot;skip&quot;  href=&quot;http://flash.manbox.be&quot;&gt;&lt;strong&gt;Accéder à la VENTE FLASH&lt;/strong&gt;&lt;/a&gt;&lt;a class=&quot;skip&quot; href=&quot;#&quot;&gt;Accéder à la version archivée de ManBox&lt;/a&gt;.
        /// </summary>
        public static string ClosedInfo {
            get {
                return ResourceManager.GetString("ClosedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les basiques.
        /// </summary>
        public static string ComposeBasicsTitle {
            get {
                return ResourceManager.GetString("ComposeBasicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composez votre Manbox &lt;a class=&quot;small show-packs&quot; href=&quot;javascript:;&quot;&gt;ou choisissez un pack&lt;/a&gt;.
        /// </summary>
        public static string ComposeCustomTitle {
            get {
                return ResourceManager.GetString("ComposeCustomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix catalogue.
        /// </summary>
        public static string ComposePacksCatalogPrice {
            get {
                return ResourceManager.GetString("ComposePacksCatalogPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir.
        /// </summary>
        public static string ComposePacksChooseBtn {
            get {
                return ResourceManager.GetString("ComposePacksChooseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre avantage.
        /// </summary>
        public static string ComposePacksDiscount {
            get {
                return ResourceManager.GetString("ComposePacksDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur combinée au prix catalogue des produits inclus dans ce pack.
        /// </summary>
        public static string ComposePacksPopover1 {
            get {
                return ResourceManager.GetString("ComposePacksPopover1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre réduction Manbox en choisissant ce pack.
        /// </summary>
        public static string ComposePacksPopover2 {
            get {
                return ResourceManager.GetString("ComposePacksPopover2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;blue-text&quot;&gt;&lt;strong&gt;Nouveau!&lt;/strong&gt;&lt;/span&gt; Des packs Manbox à prix &lt;span class=&quot;blue-text&quot;&gt;super avantageux&lt;/span&gt; 
        ///        &lt;br /&gt;Choisissez un pack, sélectionnez votre taille et voilà!   &lt;a class=&quot;small skip-packs&quot; href=&quot;javascript:;&quot;&gt;(ou composez votre pack custom)&lt;/a&gt;.
        /// </summary>
        public static string ComposePacksTitle {
            get {
                return ResourceManager.GetString("ComposePacksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez la vignette pour zoomer.
        /// </summary>
        public static string ComposePacksZoom {
            get {
                return ResourceManager.GetString("ComposePacksZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre sélection.
        /// </summary>
        public static string ComposeSelectionTitle {
            get {
                return ResourceManager.GetString("ComposeSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il manque des données dans votre demande de contact..
        /// </summary>
        public static string ContactFormMissingInfo {
            get {
                return ResourceManager.GetString("ContactFormMissingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci. Votre message a bien été envoyé..
        /// </summary>
        public static string ContactFormThx {
            get {
                return ResourceManager.GetString("ContactFormThx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        public static string ContactFrom {
            get {
                return ResourceManager.GetString("ContactFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        public static string ContactSendBtn {
            get {
                return ResourceManager.GetString("ContactSendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacter ManBox.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgique.
        /// </summary>
        public static string CountryBE {
            get {
                return ResourceManager.GetString("CountryBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string CountryFR {
            get {
                return ResourceManager.GetString("CountryFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        public static string CountryLU {
            get {
                return ResourceManager.GetString("CountryLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays-Bas.
        /// </summary>
        public static string CountryNL {
            get {
                return ResourceManager.GetString("CountryNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string CouponApplyBtn {
            get {
                return ResourceManager.GetString("CouponApplyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avez-vous un code de réduction?.
        /// </summary>
        public static string CouponShowLink {
            get {
                return ResourceManager.GetString("CouponShowLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recevoir plus tôt.
        /// </summary>
        public static string DeliveryBtnRush {
            get {
                return ResourceManager.GetString("DeliveryBtnRush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snoozer.
        /// </summary>
        public static string DeliveryBtnSnooze {
            get {
                return ResourceManager.GetString("DeliveryBtnSnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Livraison&lt;/h4&gt;
        ///        &lt;p&gt;
        ///            La livraison est effectuée via la Poste, dans une enveloppe matelassée qui rentre dans la plupart des boîtes aux lettres.&lt;br /&gt;
        ///            La livraison est gratuite pour toute commande supérieure à € 29. 
        ///        &lt;/p&gt;
        ///
        ///        &lt;h4&gt;Retour&lt;/h4&gt;
        ///        &lt;p&gt;
        ///            Vous avez 30 jours pour retourner partiellement ou totalement votre commande.&lt;br /&gt;
        ///            Renvoyer-nous le colis par la poste pour le prix de 1 ou 2 timbres seulement (selon votre comman [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeliveryModalBodyHtml {
            get {
                return ResourceManager.GetString("DeliveryModalBodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraison.
        /// </summary>
        public static string DeliveryModalTitle {
            get {
                return ResourceManager.GetString("DeliveryModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous vous envoyons votre commande dès que possible (environ 7 jours max).
        /// </summary>
        public static string DeliveryRushShippableAsap {
            get {
                return ResourceManager.GetString("DeliveryRushShippableAsap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&apos;après nos stocks nous pouvons vous envoyer votre commande dès demain!.
        /// </summary>
        public static string DeliveryRushShippableTomorrow {
            get {
                return ResourceManager.GetString("DeliveryRushShippableTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre commande a bien été retardée de {0} semaine(s) pour vous être livrée à cette date: {1}.
        /// </summary>
        public static string DeliverySnooze {
            get {
                return ResourceManager.GetString("DeliverySnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette livraison aura lieu dans plus d&apos;un mois, vous ne pouvez pas encore snoozer..
        /// </summary>
        public static string DeliverySnoozeNotYet {
            get {
                return ResourceManager.GetString("DeliverySnoozeNotYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Login.
        /// </summary>
        public static string FacebookConnectButton {
            get {
                return ResourceManager.GetString("FacebookConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ère Livraison.
        /// </summary>
        public static string FirstDelivery {
            get {
                return ResourceManager.GetString("FirstDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrivez-vous à notre newsletter.
        /// </summary>
        public static string FooterSubscribeNewsletter {
            get {
                return ResourceManager.GetString("FooterSubscribeNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer de mot de passe.
        /// </summary>
        public static string ForgottenPasswordFormSubmit {
            get {
                return ResourceManager.GetString("ForgottenPasswordFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre adresse mail ici. Nous vous enverrons un mail vous permettant de vous authentifier temporairement afin de modifier votre mot de passe..
        /// </summary>
        public static string ForgottenPasswordFormText {
            get {
                return ResourceManager.GetString("ForgottenPasswordFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié?.
        /// </summary>
        public static string ForgottenPasswordTitle {
            get {
                return ResourceManager.GetString("ForgottenPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraison gratuite.
        /// </summary>
        public static string FreeShipping {
            get {
                return ResourceManager.GetString("FreeShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marc.
        /// </summary>
        public static string GiftDefaultGuestName {
            get {
                return ResourceManager.GetString("GiftDefaultGuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour te souhaiter de merveilleuses fêtes de fin d’années, j’ai tout de suite su que ce pack cadeau était fait pour toi !.
        /// </summary>
        public static string GiftDefaultMessage {
            get {
                return ResourceManager.GetString("GiftDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cher.
        /// </summary>
        public static string GiftsDear {
            get {
                return ResourceManager.GetString("GiftsDear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir en détail.
        /// </summary>
        public static string GiftsDetailBtn {
            get {
                return ResourceManager.GetString("GiftsDetailBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Des questions sur nos packs cadeaux?&lt;/h3&gt;
        ///                &lt;a class=&quot;faq-question&quot; href=&quot;javascript:void(0)&quot;&gt;
        ///                    &lt;i class=&quot;icon-plus-sign&quot;&gt;&lt;/i&gt; En quoi consistent les packs cadeaux ManBox ?
        ///                &lt;/a&gt;
        ///                &lt;p class=&quot;faq-answer&quot;&gt;
        ///                    Les packs cadeaux ManBox sont une présélection d’articles correspondant à un profil type d’homme. Ils ne sont livrés qu’une fois. En plus d’un ensemble
        ///                    d’articles, ils contiennent également un chè [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GiftsFaq {
            get {
                return ResourceManager.GetString("GiftsFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ol&gt;
        ///                    &lt;li&gt;Choisissez votre pack cadeau selon le type d&apos;homme&lt;/li&gt;
        ///                    &lt;li&gt;Les packs cadeaux ne sont livrés qu&apos;une seule fois et contiennent un chèque-cadeau pour qu&apos;il puisse essayer la formule abonnement&lt;/li&gt;
        ///                    &lt;li&gt;
        ///                        Vous offrez le cadeau en main propre ou le faites livrer chez lui avec un message personnalisé&lt;br /&gt;
        ///                        &lt;a href=&quot;#faq&quot;&gt;&lt;i class=&quot;icon-arrow-right&quot;&gt;&lt;/i&gt; En savoir plus&lt;/a&gt;
        ///                     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GiftsHeaderList {
            get {
                return ResourceManager.GetString("GiftsHeaderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chaque homme ses besoins, à chaque homme son pack cadeau ManBox!.
        /// </summary>
        public static string GiftsHeaderParagraph {
            get {
                return ResourceManager.GetString("GiftsHeaderParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les packs cadeaux.
        /// </summary>
        public static string GiftsHeaderTitle {
            get {
                return ResourceManager.GetString("GiftsHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son prénom.
        /// </summary>
        public static string GiftsHisName {
            get {
                return ResourceManager.GetString("GiftsHisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer sa taille.
        /// </summary>
        public static string GiftsHisSize {
            get {
                return ResourceManager.GetString("GiftsHisSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + chèque cadeau de.
        /// </summary>
        public static string GiftsIncludingVoucher {
            get {
                return ResourceManager.GetString("GiftsIncludingVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offrir ce pack.
        /// </summary>
        public static string GiftsOfferBtn {
            get {
                return ResourceManager.GetString("GiftsOfferBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caractères restant.
        /// </summary>
        public static string GiftsRemainingChars {
            get {
                return ResourceManager.GetString("GiftsRemainingChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse postale pour la livraison du cadeau.
        /// </summary>
        public static string GiftsShippingAddress {
            get {
                return ResourceManager.GetString("GiftsShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chez lui directement ou chez vous pour lui offrir en main propre.
        /// </summary>
        public static string GiftsShippingAddressInfo {
            get {
                return ResourceManager.GetString("GiftsShippingAddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prix n&apos;est pas mentionné dans le paquet cadeau.
        /// </summary>
        public static string GiftsShippingPriceInfo {
            get {
                return ResourceManager.GetString("GiftsShippingPriceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message personnalisé.
        /// </summary>
        public static string GiftsYourMessage {
            get {
                return ResourceManager.GetString("GiftsYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message.
        /// </summary>
        public static string GiftsYourMessage2 {
            get {
                return ResourceManager.GetString("GiftsYourMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecrivez votre message personnel ici ou utilisez le message standard.
        /// </summary>
        public static string GiftsYourMessageInfo {
            get {
                return ResourceManager.GetString("GiftsYourMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ici.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment ça marche?.
        /// </summary>
        public static string HowItWorksTitle {
            get {
                return ResourceManager.GetString("HowItWorksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentions légales.
        /// </summary>
        public static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;ManBox est un service offert par: &lt;br /&gt;&lt;br /&gt;
        ///            &lt;strong&gt;
        ///                COZYPIXEL SPRL&lt;br /&gt;
        ///                Avenue Victor Rousseau, 13&lt;br /&gt;
        ///                1190 Bruxelles&lt;/strong&gt;&lt;br /&gt;&lt;br /&gt;
        ///                Téléphone: 02 344 07 24&lt;br /&gt;
        ///                Email: info@manbox.be&lt;br /&gt;
        ///                Directeur: Thibaut Nguyen&lt;br /&gt;
        ///                Enregistré au tribunal de commerce de Bruxelles le 4 février 2013&lt;br /&gt;
        ///                Numéro d&apos;entreprise et TVA : BE 0503772171&lt;br /&gt;&lt;/p&gt;.
        /// </summary>
        public static string ImprintText {
            get {
                return ResourceManager.GetString("ImprintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre panier est invalide...
        /// </summary>
        public static string InvalidSubscription {
            get {
                return ResourceManager.GetString("InvalidSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créez votre ManBox .
        /// </summary>
        public static string LandingCreateBoxBtn {
            get {
                return ResourceManager.GetString("LandingCreateBoxBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sans engagements, retours gratuits.
        /// </summary>
        public static string LandingCreateBoxInfo {
            get {
                return ResourceManager.GetString("LandingCreateBoxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les clients existants peuvent s&apos;authentifier.
        /// </summary>
        public static string LandingExistingCustomersMayLogin {
            get {
                return ResourceManager.GetString("LandingExistingCustomersMayLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou suivez-nous sur.
        /// </summary>
        public static string LandingFollowUsOn {
            get {
                return ResourceManager.GetString("LandingFollowUsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offrez une manbox personnalisée.
        /// </summary>
        public static string LandingGiftsInfo {
            get {
                return ResourceManager.GetString("LandingGiftsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManBox en cadeau.
        /// </summary>
        public static string LandingGoToGifts {
            get {
                return ResourceManager.GetString("LandingGoToGifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAVITAILLEMENT EN ESSENTIELS MASCULINS.
        /// </summary>
        public static string LandingHeaderTitle {
            get {
                return ResourceManager.GetString("LandingHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxers, chaussettes, rasoirs, préservatifs livrés chez vous tous les 3 mois.
        /// </summary>
        public static string LandingHeaderTitle2 {
            get {
                return ResourceManager.GetString("LandingHeaderTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string LandingNotifyMe {
            get {
                return ResourceManager.GetString("LandingNotifyMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un ensemble d&apos;articles que vous souhaitez recevoir régulièrement. Du &lt;a  href=&quot;{0}&quot;&gt;caleçon&lt;/a&gt; aux &lt;a  href=&quot;{0}&quot;&gt;préservatifs&lt;/a&gt; il y a toujours quelque chose dont vous manquez..
        /// </summary>
        public static string LandingSecondary1Content {
            get {
                return ResourceManager.GetString("LandingSecondary1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composez votre ManBox.
        /// </summary>
        public static string LandingSecondary1Title {
            get {
                return ResourceManager.GetString("LandingSecondary1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes réapprovisionné avec les articles choisis. Une semaine avant livraison, vous recevez une notification. Vous pouvez alors modifier votre &lt;a  href=&quot;{0}&quot;&gt;Manbox&lt;/a&gt;..
        /// </summary>
        public static string LandingSecondary2Content {
            get {
                return ResourceManager.GetString("LandingSecondary2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les 3 mois.
        /// </summary>
        public static string LandingSecondary2Title {
            get {
                return ResourceManager.GetString("LandingSecondary2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez à tout moment annuler votre abonnement, modifier votre Manbox ou reporter sa livraison. Pas satisfait? Retournez votre commande dans les 30 jours..
        /// </summary>
        public static string LandingSecondary3Content {
            get {
                return ResourceManager.GetString("LandingSecondary3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous gérez.
        /// </summary>
        public static string LandingSecondary3Title {
            get {
                return ResourceManager.GetString("LandingSecondary3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous sommes bientôt de retour. Laissez-nous votre email afin d&apos;être prévenu de la réouverture..
        /// </summary>
        public static string LandingSoonSubtitle {
            get {
                return ResourceManager.GetString("LandingSoonSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous ajustons nos stocks. Merci pour votre patience!.
        /// </summary>
        public static string LandingSoonTitle {
            get {
                return ResourceManager.GetString("LandingSoonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crée ta ManBox avec slips, chaussettes etc..
        /// </summary>
        public static string LandingStep1 {
            get {
                return ResourceManager.GetString("LandingStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les 3 mois tu en reçois une nouvelle.
        /// </summary>
        public static string LandingStep2 {
            get {
                return ResourceManager.GetString("LandingStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relax! Tu gères comme bon te semble.
        /// </summary>
        public static string LandingStep3 {
            get {
                return ResourceManager.GetString("LandingStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moins de détails.
        /// </summary>
        public static string LessDetail {
            get {
                return ResourceManager.GetString("LessDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous n&apos;avons pu vous authentifier. Veuillez vérifier vos données..
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désauthentification.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre ManBox est prête.
        /// </summary>
        public static string MailShipmentConfirmationSubject {
            get {
                return ResourceManager.GetString("MailShipmentConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Félicitations vous allez bientôt recevoir votre première ManBox.
        /// </summary>
        public static string MailSubscriptionConfirmationSubject {
            get {
                return ResourceManager.GetString("MailSubscriptionConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manbox votre box pour homme par abonnement. Livraison régulière en slip, boxers, caleçon, rasoir, chaussettes, préservatifs, sous-vêtements, soins du corps.
        /// </summary>
        public static string ManBoxDescTag {
            get {
                return ResourceManager.GetString("ManBoxDescTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manbox,slip, slips, caleçon, rasoir,chaussettes, boxers,préservatifs,rasoirs,sous-vêtements,essentiels,homme,renouvellement,box,abonnement,ravitaillement,livraison.
        /// </summary>
        public static string ManBoxKeywordsTag {
            get {
                return ResourceManager.GetString("ManBoxKeywordsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManBox – Slip, chaussettes, rasoir par abonnement.
        /// </summary>
        public static string ManBoxTitleTag {
            get {
                return ResourceManager.GetString("ManBoxTitleTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue.
        /// </summary>
        public static string MenuCompose {
            get {
                return ResourceManager.GetString("MenuCompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadeaux.
        /// </summary>
        public static string MenuGifts {
            get {
                return ResourceManager.GetString("MenuGifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle.
        /// </summary>
        public static string ModelSize {
            get {
                return ResourceManager.GetString("ModelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifer.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir cet article.
        /// </summary>
        public static string MoreDetail {
            get {
                return ResourceManager.GetString("MoreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau mot de passe.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répétez le nouveau mot de passe.
        /// </summary>
        public static string NewPasswordRepeat {
            get {
                return ResourceManager.GetString("NewPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas encore membre?.
        /// </summary>
        public static string NotSubscribedYet {
            get {
                return ResourceManager.GetString("NotSubscribedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro.
        /// </summary>
        public static string OrderReference {
            get {
                return ResourceManager.GetString("OrderReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous venons de vous envoyer un email contenant un lien vous permettant de vous authentifier..
        /// </summary>
        public static string PasswordResetMailSent {
            get {
                return ResourceManager.GetString("PasswordResetMailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer.
        /// </summary>
        public static string PayBtn {
            get {
                return ResourceManager.GetString("PayBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Paymill_field_cancel_3ds {
            get {
                return ResourceManager.GetString("Paymill_field_cancel_3ds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de vérification invalide.
        /// </summary>
        public static string Paymill_field_invalid_card_cvc {
            get {
                return ResourceManager.GetString("Paymill_field_invalid_card_cvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;expiration invalide.
        /// </summary>
        public static string Paymill_field_invalid_card_exp {
            get {
                return ResourceManager.GetString("Paymill_field_invalid_card_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de carte invalide.
        /// </summary>
        public static string Paymill_field_invalid_card_number {
            get {
                return ResourceManager.GetString("Paymill_field_invalid_card_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonnement ManBox.
        /// </summary>
        public static string PayPalManBoxSubscription {
            get {
                return ResourceManager.GetString("PayPalManBoxSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous vous redirigeons maintenant vers PayPal.
        /// </summary>
        public static string PayPalRedirectingMsg {
            get {
                return ResourceManager.GetString("PayPalRedirectingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidentialité.
        /// </summary>
        public static string PrivacyTerms {
            get {
                return ResourceManager.GetString("PrivacyTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;MANBOX traite toutes les informations concernant sa clientèle avec la plus stricte confidentialité.&lt;/p&gt;
        ///
        ///&lt;p&gt;Lors de la commande, seules sont demandées les informations indispensables (nom, prénom, adresse, e-mail) pour un traitement efficace et un suivi attentif de la commande ou de la souscription de l’abonnement. Les données bancaires sont stockées et cryptées par une tierce partie, sur un serveur sécurisé.&lt;/p&gt;
        ///
        ///&lt;h3&gt;Cookies et données collectées lors de la navigation&lt;/h3&gt;
        ///&lt;p&gt;Un cookie est un petit [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrivacyTermsText {
            get {
                return ResourceManager.GetString("PrivacyTermsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a un problème pour vous inscrire. Si vous êtes déjà membre, vous pouvez vous authentifier ou établir un nouveau mot de passe.
        /// </summary>
        public static string RegisterAlreadyMember {
            get {
                return ResourceManager.GetString("RegisterAlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2ème Livraison.
        /// </summary>
        public static string SecondDelivery {
            get {
                return ResourceManager.GetString("SecondDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endéans 7 jours.
        /// </summary>
        public static string ShippedWithinWeek {
            get {
                return ResourceManager.GetString("ShippedWithinWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;trust-info&quot;&gt;
        ///            &lt;h3&gt;&lt;i class=&quot;icon-check&quot;&gt;&lt;/i&gt; Satisfait ou remboursé&lt;/h3&gt;
        ///            &lt;p&gt;
        ///                Un article ne vous convient pas? Vous avez jusqu&apos;à &lt;strong&gt;30 jours&lt;/strong&gt; pour nous le renvoyer.
        ///            &lt;/p&gt;
        ///        &lt;/div&gt;
        ///
        ///        &lt;div class=&quot;trust-info&quot;&gt;
        ///            &lt;h3&gt;&lt;i class=&quot;icon-check&quot;&gt;&lt;/i&gt; Changé d&apos;avis?&lt;/h3&gt;
        ///            &lt;p&gt;
        ///                Aucun souci. Vous pouvez annuler votre abonnement à tout moment.    
        ///            &lt;/p&gt;
        ///        &lt;/div&gt;
        ///
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ShippingTrustInfoHtml {
            get {
                return ResourceManager.GetString("ShippingTrustInfoHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;table table-hover&quot;&gt;
        ///            &lt;tr&gt;
        ///                &lt;td colspan=&quot;4&quot;&gt;&lt;strong&gt;Sous vêtements&lt;/strong&gt;&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;Tour de taille en cm&lt;/td&gt;
        ///                &lt;td colspan=&quot;3&quot;&gt;Taille&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;69/76&lt;/td&gt;
        ///                &lt;td&gt;36/38&lt;/td&gt;
        ///                &lt;td&gt;1&lt;/td&gt;
        ///                &lt;td&gt;S&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;77/84&lt;/td&gt;
        ///                &lt;td&gt;40/42&lt;/td&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SizeChartBodyHtml {
            get {
                return ResourceManager.GetString("SizeChartBodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide des tailles.
        /// </summary>
        public static string SizeChartModalTitle {
            get {
                return ResourceManager.GetString("SizeChartModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci pour votre inscription! .
        /// </summary>
        public static string SubscribeSuccess {
            get {
                return ResourceManager.GetString("SubscribeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions Générales.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;p&gt;Les présentes conditions générales de vente (ci-après les « CGV ») sont soumises à la loi belge.&lt;/p&gt;
        ///
        ///        &lt;p&gt;Les présentes CGV (et les documents auxquels elles font référence) vous informent sur les modalités et les conditions générales de vente dans lesquelles nous fournissons des services (ci-après, les « Services »), notamment par le biais de la souscription à un abonnement Manbox permettant de recevoir des boîtes  de produits cosmétiques sous forme de miniatures sélectionnés par MANBO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TermsAndConditionsText {
            get {
                return ResourceManager.GetString("TermsAndConditionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce que nos clients disent de nous.
        /// </summary>
        public static string TestimonialsTitle {
            get {
                return ResourceManager.GetString("TestimonialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La modification de votre abonnement a bien été prise en comtpe..
        /// </summary>
        public static string ThankYouModificationText {
            get {
                return ResourceManager.GetString("ThankYouModificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci. Nous vous expédions votre première Manbox au plus tôt..
        /// </summary>
        public static string ThankYouText {
            get {
                return ResourceManager.GetString("ThankYouText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour toute question sur votre commande, n&apos;hésitez pas à nous contacter sur &lt;a href=&quot;mailto:support@manbox.be&quot;&gt;support@manbox.be&lt;/a&gt; ou via le chat..
        /// </summary>
        public static string ThankYouText2 {
            get {
                return ResourceManager.GetString("ThankYouText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;A bientôt!&lt;/strong&gt;&lt;br /&gt;
        ///L&apos;équipe Manbox.
        /// </summary>
        public static string ThankYouText3 {
            get {
                return ResourceManager.GetString("ThankYouText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci!.
        /// </summary>
        public static string ThankYouTitle {
            get {
                return ResourceManager.GetString("ThankYouTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes désinscrit.
        /// </summary>
        public static string UnsubscribedMessage {
            get {
                return ResourceManager.GetString("UnsubscribedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre prochaine ManBox arrive !.
        /// </summary>
        public static string UpcomingBoxNotificationMailSubject {
            get {
                return ResourceManager.GetString("UpcomingBoxNotificationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour les cartes MasterCard et Visa, vous trouverez le code à 3 chiffres au verso de votre carte sur la zone de signature..
        /// </summary>
        public static string VerifCodeModalBodyHtml {
            get {
                return ResourceManager.GetString("VerifCodeModalBodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de vérification de la carte.
        /// </summary>
        public static string VerifCodeModalTitle {
            get {
                return ResourceManager.GetString("VerifCodeModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salut {0}. Authentifiez-vous afin d&apos;accéder à votre ManBox..
        /// </summary>
        public static string WelcomeBackLogIn {
            get {
                return ResourceManager.GetString("WelcomeBackLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre cadeau de bienvenue  ManBox.
        /// </summary>
        public static string WelcomeMailCouponSubject {
            get {
                return ResourceManager.GetString("WelcomeMailCouponSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recevoir un coupon de 3€.
        /// </summary>
        public static string WelcomeModalCta {
            get {
                return ResourceManager.GetString("WelcomeModalCta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///                &lt;li&gt;Choisissez vos slips et chaussettes&lt;/li&gt;
        ///                &lt;li&gt;Commandez on vous envoie ça direct&lt;/li&gt;
        ///                &lt;li&gt;Plus tard on voit avec vous ce qu&apos;on renouvelle&lt;/li&gt;
        ///            &lt;/ul&gt;.
        /// </summary>
        public static string WelcomeModalMsgList {
            get {
                return ResourceManager.GetString("WelcomeModalMsgList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de spam. Promis, juré, craché !.
        /// </summary>
        public static string WelcomeModalNoSpam {
            get {
                return ResourceManager.GetString("WelcomeModalNoSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonnez-vous à notre newsletter et recevez déjà 3 € de réduction!.
        /// </summary>
        public static string WelcomeModalSubscribe {
            get {
                return ResourceManager.GetString("WelcomeModalSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Inscrit!&lt;/strong&gt; Vous avez reçu un code coupon par email..
        /// </summary>
        public static string WelcomeModalSubscribeSuccess {
            get {
                return ResourceManager.GetString("WelcomeModalSubscribeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vos données.
        /// </summary>
        public static string YourDataTitle {
            get {
                return ResourceManager.GetString("YourDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre commande.
        /// </summary>
        public static string YourOrder {
            get {
                return ResourceManager.GetString("YourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vos commandes.
        /// </summary>
        public static string YourOrderHistory {
            get {
                return ResourceManager.GetString("YourOrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //www.youtube.com/embed/ZLDipwpDDlQ?hd=1&amp;rel=0&amp;autohide=1&amp;showinfo=0&amp;autoplay=1.
        /// </summary>
        public static string YoutubeVideoUrl {
            get {
                return ResourceManager.GetString("YoutubeVideoUrl", resourceCulture);
            }
        }
    }
}
