//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManBox.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Users = new HashSet<User>();
            this.Newsletters = new HashSet<Newsletter>();
        }
    
        public int CountryId { get; set; }
        public string Name { get; set; }
        public decimal VatPercentage { get; set; }
        public string CurrencyCV { get; set; }
        public string IsoCode { get; set; }
        public decimal ShippingFee { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Newsletter> Newsletters { get; set; }
    }
}
