//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManBox.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.TranslationTexts = new HashSet<TranslationText>();
            this.Users = new HashSet<User>();
            this.Newsletters = new HashSet<Newsletter>();
        }
    
        public int LanguageId { get; set; }
        public string IsoCode { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TranslationText> TranslationTexts { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Newsletter> Newsletters { get; set; }
    }
}
