//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManBox.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pack
    {
        public Pack()
        {
            this.ProductPacks = new HashSet<ProductPack>();
            this.SubscriptionDeliveryModels = new HashSet<SubscriptionDeliveryModel>();
        }
    
        public int PackId { get; set; }
        public System.Guid TitleTrId { get; set; }
        public System.Guid DescrTrId { get; set; }
        public decimal ShopPrice { get; set; }
        public decimal SupplierPrice { get; set; }
        public Nullable<decimal> AdvisedPrice { get; set; }
        public bool IsAGift { get; set; }
        public Nullable<decimal> GiftVoucherValue { get; set; }
        public int Position { get; set; }
    
        public virtual Translation Translation { get; set; }
        public virtual Translation Translation1 { get; set; }
        public virtual ICollection<ProductPack> ProductPacks { get; set; }
        public virtual ICollection<SubscriptionDeliveryModel> SubscriptionDeliveryModels { get; set; }
    }
}
