//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManBox.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Models = new HashSet<Model>();
            this.ProductPacks = new HashSet<ProductPack>();
        }
    
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsVisible { get; set; }
        public string Reference { get; set; }
        public string DescriptionDetail { get; set; }
        public Nullable<int> BrandId { get; set; }
        public int Position { get; set; }
        public System.Guid TitleTrId { get; set; }
        public System.Guid DescriptionTrId { get; set; }
        public System.Guid DescriptionDetailTrId { get; set; }
        public int NumberOfPictures { get; set; }
        public string VineUrl { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Model> Models { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Translation Translation { get; set; }
        public virtual Translation Translation1 { get; set; }
        public virtual Translation Translation11 { get; set; }
        public virtual ICollection<ProductPack> ProductPacks { get; set; }
    }
}
