//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManBox.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionDelivery
    {
        public SubscriptionDelivery()
        {
            this.SubscriptionDeliveryModels = new HashSet<SubscriptionDeliveryModel>();
            this.SubscriptionDeliveryMessages = new HashSet<SubscriptionDeliveryMessage>();
        }
    
        public int SubscriptionDeliveryId { get; set; }
        public int SubscriptionId { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public System.DateTime QueuedDatetime { get; set; }
        public string DeliveryStateCV { get; set; }
        public string DeliveryPaymentStatusCV { get; set; }
        public decimal Amount { get; set; }
        public decimal ShippingFee { get; set; }
        public decimal CouponAmount { get; set; }
        public Nullable<int> CouponId { get; set; }
    
        public virtual ICollection<SubscriptionDeliveryModel> SubscriptionDeliveryModels { get; set; }
        public virtual Subscription Subscription { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual ICollection<SubscriptionDeliveryMessage> SubscriptionDeliveryMessages { get; set; }
    }
}
