//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManBox.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionDeliveryModel
    {
        public int ModelId { get; set; }
        public int SubscriptionDeliveryId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> PackId { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual SubscriptionDelivery SubscriptionDelivery { get; set; }
        public virtual Pack Pack { get; set; }
    }
}
