//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManBox.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.SubscriptionDeliveries = new HashSet<SubscriptionDelivery>();
        }
    
        public int SubscriptionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Token { get; set; }
        public Nullable<int> InvoiceAddressId { get; set; }
        public Nullable<int> ShippingAddressId { get; set; }
        public bool IsActive { get; set; }
        public bool IsPaused { get; set; }
        public string SubscriptionStateCV { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<System.DateTime> NextDeliveryDate { get; set; }
        public string PayPalSenderEmail { get; set; }
        public string PayPalPreapprovalKey { get; set; }
        public string PaymillPayId { get; set; }
        public string PaymillToken { get; set; }
        public string PaymillClientId { get; set; }
        public Nullable<int> GiftId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<SubscriptionDelivery> SubscriptionDeliveries { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address ShippingAddress { get; set; }
        public virtual Gift Gift { get; set; }
    }
}
