//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManBox.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public Translation()
        {
            this.Products = new HashSet<Product>();
            this.TranslationTexts = new HashSet<TranslationText>();
            this.Categories = new HashSet<Category>();
            this.Products1 = new HashSet<Product>();
            this.Products11 = new HashSet<Product>();
            this.Packs = new HashSet<Pack>();
            this.Packs1 = new HashSet<Pack>();
        }
    
        public System.Guid TranslationId { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<TranslationText> TranslationTexts { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual ICollection<Product> Products11 { get; set; }
        public virtual ICollection<Pack> Packs { get; set; }
        public virtual ICollection<Pack> Packs1 { get; set; }
    }
}
