//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManBox.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslationText
    {
        public System.Guid TranslationId { get; set; }
        public int LanguageId { get; set; }
        public string Text { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Translation Translation { get; set; }
    }
}
